### ISSUE TITLE
Create function to return number

### ISSUE THREAD

**Issue by 7p7p7p** [rkoudsi/dice_simulator#5]
Create a function with these specifications: 
- The function is contained in the file "Introduction.py"
- the name is `roll`
- has no parameters
- returns a number in the range 1 to 6 inclusive

**Comment by 7p7p7p** [comment]
@emarkworth this issue is not complete. You can see the file `Introduction.py` [here](https://github.com/rkoudsi/dice_simulator/blob/2c673e70f9eb913688c51d4bc1c73bcf91719fed/Introduction.py) (shown at the time I write this comment) and it's an empty file.  
Perhaps you made the change locally but did not push to the server?  
Reopening this issue.

**Comment by emarkworth** [comment]
ah yes. So I edited the py file through anaconda navigator, does it work to somehow push it through from terminal or are there more steps

**Comment by 7p7p7p** [comment]
yes you should push it through the terminal. You can use the terminal commands mentioned in a previous issue [here](https://github.com/rkoudsi/dice_simulator/issues/4#issuecomment-1105886590).  
Note some important git commands (after `cd`ing into the directory. 
- `git status` to show changed files. Make sure its only what you expect to be changed. No more no less. 
- `git diff file` where `file` is the name of a changed file shown in the previous `git status` command. This `git diff ...` command will show you the exact contents of the file that had changed.
